# Copyright (c) 2023 SolarWinds, LLC.
# All rights reserved.

name: Build publish lambda layer

on:
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  # build layer on arm64 and amd64, then upload to artifacts
  build_layer:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - arm64

    runs-on: ${{ matrix.arch == 'arm64' && fromJSON('{"group":"apm-arm-runner"}') || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v3

      # Install additional package for self runner
      - name: Install additional package for ${{ matrix.arch }}
        if: ${{ matrix.arch == 'arm64'}}
        run: |
          sudo apt-get update
          echo y | sudo apt-get upgrade
          echo y | sudo apt-get install python3.10-venv

      - uses: aws-actions/setup-sam@v2

      # Build inside Docker containers
      # -u in sam build will automatically set LAMBDA_TASK_ROOT (see: https://github.com/aws/aws-sam-cli/issues/3407)
      - name: build lambda layer
        run: |
          uname -a
          cd lambda/
          sam build -u -t template.yml -e BUNDLE_RUBYGEMS__PKG__GITHUB__COM=$GITHUB_RUBY_TOKEN --parameter-overrides LayerArchitecture=${{ matrix.arch }}
          ./zip_layer.sh -n ruby-layer-${{ matrix.arch }}
        env:
          GITHUB_RUBY_TOKEN: ${{ secrets.PACKAGE_GITHUB_TOKEN }}

      - name: Upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: ruby-layer-${{ matrix.arch }}.zip
          path: lambda

  # extract the built layer from artifacts, then publish it based on region
  publish_layer:
    needs:
      - build_layer
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        aws_region: 
          - us-east-1
        arch:
          - x86_64
          - arm64
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.LAMBDA_PUBLISHER_ARN }}
          aws-region: ${{ matrix.aws_region }}

      - name: extract layer zip from artifacts
        uses: actions/download-artifact@v4
        with:
          name: ruby-layer-${{ matrix.arch }}.zip
          path: lambda

      - name: extract current solarwinds_apm version
        run: |
          APM_VERSION=$(grep "gem 'solarwinds_apm'" lambda/layer/Gemfile | awk -F"'" '{print $4}')
          APM_VERSION="${APM_VERSION//./_}"
          echo "SOLARWINDS_APM_VERSION=$APM_VERSION" >> $GITHUB_ENV

      - name: publish lambda layer
        run: |
          cd lambda/
          aws lambda publish-layer-version \
            --layer-name solarwinds-apm-ruby-${{ matrix.arch }}-$SOLARWINDS_APM_VERSION \
            --license-info "Apache 2.0" \
            --compatible-architectures ${{ matrix.arch }} \
            --compatible-runtimes ruby3.2 \
            --zip-file fileb://ruby-layer-${{ matrix.arch }}.zip \
            --query 'LayerVersionArn' \
            --compatible-architectures ${{ matrix.arch }} \
            --output text

      - name: grant permissions to public for the published layer
        run: |
          layer_name=solarwinds-apm-ruby-${{ matrix.arch }}-$SOLARWINDS_APM_VERSION
          latest_version=$(aws lambda list-layer-versions --layer-name $layer_name | jq -r '.LayerVersions | max_by(.Version) | .Version')
          aws lambda add-layer-version-permission \
            --layer-name $layer_name \
            --statement-id apm-ruby-add-permission \
            --action lambda:GetLayerVersion \
            --principal '*' \
            --version-number $latest_version \
            --output text
